services:
  web:
    build:
      target: builder-dev
    ports:
      - "3000:3000"
    volumes:
      # binding package.json for each workspace and the root.
      # binding src/ for each workspace used here (web related)
      - ./package.json:/home/node/app/package.json
      - ./apps/web/src:/home/node/app/apps/web/src
      - ./apps/web/package.json:/home/node/app/apps/web/package.json
      - ./packages/lib-ui/src:/home/node/app/packages/lib-ui/src
      - ./packages/lib-ui/package.json:/home/node/app/packages/lib-ui/package.json
      - ./packages/lib-shared/src:/home/node/app/packages/lib-shared/src
      - ./packages/lib-shared/package.json:/home/node/app/packages/lib-shared/package.json
    tty: true
    environment:
      PORT: 3000
      NODE_ENV: development
    command: npm run dev # default, but we'll set it anyway
