name: "@potatoes/app: Publish"

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci -w packages/lib-main -w packages/lib-shared -w apps/main
      - run: npm run build -w apps/app
      - run: npm publish -w apps/app
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}