name: PR to main

on:
  pull_request:
    branches: [main]

jobs:
  test-all:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/test-all.yaml
    secrets: inherit
