name: Run lib-ui tests

on:
  workflow_call:

jobs:
  test-runtime:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ts-test'
      - name: Install Dependencies
        run: npm ci
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.IF_YOU_NEED_THIS_FOR_PRIVATE_PKGS }}
      - name: Build
        run: npx tsc --build
      - name: Run tests
        run: npm run test
