name: "@potatoes/web: PR to main"

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'packages/lib-{ui,shared}/**'

jobs:
  test:
    # PRs in draft mode or commits containing #skip will not trigger action.
    if: ${{github.event.pull_request.draft == false && !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/web-test.yaml
    secrets: inherit
